DROP DATABASE IF EXISTS CarRentals;

CREATE DATABASE CarRentals;

USE CarRentals;

CREATE TABLE Customer(
Cust_ID INT(6) NOT NULL AUTO_INCREMENT,
LastName VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
Address VARCHAR(255) NOT NULL,
PhoneNum VARCHAR(50) NOT NULL, 
Email VARCHAR(255) NOT NULL,
License_No VARCHAR(20) NOT NULL,
Country_Of_Issue VARCHAR(50) NOT NULL, 
PRIMARY KEY (Cust_ID)
)  ENGINE INNODB;


CREATE TABLE Staff (
Staff_ID INT (6) AUTO_INCREMENT NOT NULL,
LastName VARCHAR (30) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
_Position VARCHAR (50) NOT NULL,
Address VARCHAR (50) NOT NULL,
Monthly_Target DECIMAL (6,2) NOT NULL,
Store_ID INT(6) NOT NULL,
PRIMARY KEY (Staff_ID),
FOREIGN KEY (Store_ID) REFERENCES Store(Store_ID)

) ENGINE INNODB;


CREATE TABLE Cars (
Reg_Num VARCHAR (20) NOT NULL,
Make VARCHAR (25) NOT NULL,
Model VARCHAR (25) NOT NULL,
Colour VARCHAR (25) NOT NULL,
_Year YEAR NOT NULL,
PRIMARY KEY (Reg_Num)
) ENGINE INNODB;

CREATE TABLE Store (
Store_ID INT(6) NOT NULL AUTO_INCREMENT,
Location VARCHAR(50) NOT NULL,
Address VARCHAR (50) NOT NULL, 
Store_Num INT(25) NOT NULL,
PRIMARY KEY (Store_ID)

)  ENGINE INNODB;

CREATE TABLE Rentals_Returns (

Rental_ID INT(6) NOT NULL AUTO_INCREMENT,
Rent_Date DATETIME NOT NULL,
Return_Date DATETIME NOT NULL,
Rental_Rate DECIMAL (6, 2) NOT NULL,
Car_Damage BOOLEAN NOT NULL,
Returned_On_Time BOOLEAN NOT NULL,
Cust_ID INT(6) NOT NULL,
Staff_ID INT(6) NOT NULL,
Reg_Num VARCHAR(20) NOT NULL,
Store_ID INT(6) NOT NULL,
PRIMARY KEY (Rental_ID),
FOREIGN KEY (Cust_ID) REFERENCES Customer (Cust_ID),
FOREIGN KEY (Staff_ID) REFERENCES Staff (Staff_ID),
FOREIGN KEY (Reg_Num) REFERENCES Cars (Reg_Num),
FOREIGN KEY (Store_ID) REFERENCES Store(Store_ID)

) ENGINE INNODB;

-- show tables;
-- SELECT * FROM Staff;

-- ALTER TABLE Staff
-- ADD Store_ID INT (6) NOT NULL After Monthly_Target;


